-- BDY1103 - Evaluacion Parcial 1
-- Caso: TechMarket SpA - Analisis de ventas, beneficios y control comercial
-- Script 00: modelo base

SET SERVEROUTPUT ON;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE auditoria_beneficios CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE bitacora_beneficios CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE detalle_venta CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE venta CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE producto CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE cliente CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE sucursal CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE sucursal (
    id_sucursal NUMBER(4) CONSTRAINT pk_sucursal PRIMARY KEY,
    nombre      VARCHAR2(80) NOT NULL,
    comuna      VARCHAR2(80) NOT NULL
);

CREATE TABLE cliente (
    id_cliente      NUMBER(6) CONSTRAINT pk_cliente PRIMARY KEY,
    nombre          VARCHAR2(120) NOT NULL,
    correo          VARCHAR2(150) CONSTRAINT uq_cliente_correo UNIQUE,
    estado          VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL,
    fecha_registro  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT ck_cliente_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE producto (
    id_producto     NUMBER(6) CONSTRAINT pk_producto PRIMARY KEY,
    nombre_producto VARCHAR2(120) NOT NULL,
    categoria       VARCHAR2(60) NOT NULL,
    precio          NUMBER(12,2) NOT NULL,
    stock           NUMBER(8) DEFAULT 0 NOT NULL,
    CONSTRAINT ck_producto_precio CHECK (precio > 0),
    CONSTRAINT ck_producto_stock CHECK (stock >= 0)
);

CREATE TABLE venta (
    id_venta     NUMBER(8) CONSTRAINT pk_venta PRIMARY KEY,
    id_sucursal  NUMBER(4) NOT NULL,
    id_cliente   NUMBER(6) NOT NULL,
    fecha_venta  DATE NOT NULL,
    total        NUMBER(14,2) NOT NULL,
    CONSTRAINT fk_venta_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal),
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT ck_venta_total CHECK (total >= 0)
);

CREATE TABLE detalle_venta (
    id_detalle      NUMBER(10) CONSTRAINT pk_detalle_venta PRIMARY KEY,
    id_venta        NUMBER(8) NOT NULL,
    id_producto     NUMBER(6) NOT NULL,
    cantidad        NUMBER(6) NOT NULL,
    precio_unitario NUMBER(12,2) NOT NULL,
    CONSTRAINT fk_detalle_venta FOREIGN KEY (id_venta) REFERENCES venta(id_venta),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto),
    CONSTRAINT ck_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_precio CHECK (precio_unitario > 0)
);

CREATE TABLE bitacora_beneficios (
    id_bitacora          NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_bitacora_beneficios PRIMARY KEY,
    id_cliente           NUMBER(6) NOT NULL,
    id_sucursal          NUMBER(4) NOT NULL,
    periodo_desde        DATE NOT NULL,
    periodo_hasta        DATE NOT NULL,
    cantidad_compras     NUMBER(6) NOT NULL,
    total_compras        NUMBER(14,2) NOT NULL,
    categoria_cliente    VARCHAR2(20) NOT NULL,
    porcentaje_beneficio NUMBER(5,2) NOT NULL,
    fecha_proceso        DATE DEFAULT SYSDATE NOT NULL,
    usuario_bd           VARCHAR2(128),
    fecha_actualizacion  DATE,
    CONSTRAINT fk_bitacora_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_bitacora_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal)
);

CREATE TABLE auditoria_beneficios (
    id_auditoria     NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_auditoria_beneficios PRIMARY KEY,
    id_bitacora      NUMBER,
    operacion        VARCHAR2(10) NOT NULL,
    usuario_bd       VARCHAR2(128) NOT NULL,
    fecha_evento     DATE DEFAULT SYSDATE NOT NULL,
    categoria_anterior VARCHAR2(20),
    categoria_nueva    VARCHAR2(20),
    total_anterior     NUMBER(14,2),
    total_nuevo        NUMBER(14,2)
);

CREATE INDEX idx_venta_sucursal_fecha ON venta(id_sucursal, fecha_venta);
CREATE INDEX idx_venta_cliente ON venta(id_cliente);
CREATE INDEX idx_detalle_venta ON detalle_venta(id_venta);


INSERT INTO sucursal VALUES (10, 'Antonio Varas', 'Providencia');
INSERT INTO sucursal VALUES (20, 'Plaza Oeste', 'Cerrillos');
INSERT INTO sucursal VALUES (30, 'Vina Centro', 'Vina del Mar');

INSERT INTO cliente VALUES (101, 'Ana Torres', 'ana.torres@correo.cl', 'ACTIVO', DATE '2026-01-15');
INSERT INTO cliente VALUES (102, 'Pedro Diaz', 'pedro.diaz@correo.cl', 'ACTIVO', DATE '2026-02-10');
INSERT INTO cliente VALUES (103, 'Maria Soto', 'maria.soto@correo.cl', 'ACTIVO', DATE '2026-03-05');
INSERT INTO cliente VALUES (104, 'Carlos Rojas', 'carlos.rojas@correo.cl', 'ACTIVO', DATE '2026-03-20');
INSERT INTO cliente VALUES (105, 'Sofia Perez', 'sofia.perez@correo.cl', 'INACTIVO', DATE '2026-04-02');

INSERT INTO producto VALUES (1001, 'Notebook Pro 14', 'Notebook', 899990, 12);
INSERT INTO producto VALUES (1002, 'Monitor 27 IPS', 'Monitor', 239990, 25);
INSERT INTO producto VALUES (1003, 'Teclado mecanico', 'Periferico', 79990, 40);
INSERT INTO producto VALUES (1004, 'Mouse inalambrico', 'Periferico', 39990, 60);
INSERT INTO producto VALUES (1005, 'SSD NVMe 1TB', 'Almacenamiento', 109990, 30);

-- Agosto 2026 - Sucursal 10
INSERT INTO venta VALUES (5001, 10, 101, DATE '2026-08-03', 899990);
INSERT INTO venta VALUES (5002, 10, 101, DATE '2026-08-12', 279980);
INSERT INTO venta VALUES (5003, 10, 101, DATE '2026-08-25', 159980);
INSERT INTO venta VALUES (5004, 10, 102, DATE '2026-08-07', 239990);
INSERT INTO venta VALUES (5005, 10, 102, DATE '2026-08-19', 519970);
INSERT INTO venta VALUES (5006, 10, 103, DATE '2026-08-11', 219980);
INSERT INTO venta VALUES (5007, 10, 104, DATE '2026-08-15', 1599800);

-- Agosto 2026 - Sucursal 20
INSERT INTO venta VALUES (5010, 20, 101, DATE '2026-08-05', 109990);
INSERT INTO venta VALUES (5011, 20, 103, DATE '2026-08-17', 319970);

-- Septiembre 2026 - Sucursal 10 (para probar otro periodo)
INSERT INTO venta VALUES (5020, 10, 102, DATE '2026-09-02', 39990);

INSERT INTO detalle_venta VALUES (9001, 5001, 1001, 1, 899990);
INSERT INTO detalle_venta VALUES (9002, 5002, 1002, 1, 239990);
INSERT INTO detalle_venta VALUES (9003, 5002, 1004, 1, 39990);
INSERT INTO detalle_venta VALUES (9004, 5003, 1003, 2, 79990);
INSERT INTO detalle_venta VALUES (9005, 5004, 1002, 1, 239990);
INSERT INTO detalle_venta VALUES (9006, 5005, 1001, 1, 479980);
INSERT INTO detalle_venta VALUES (9007, 5005, 1004, 1, 39990);
INSERT INTO detalle_venta VALUES (9008, 5006, 1005, 2, 109990);
INSERT INTO detalle_venta VALUES (9009, 5007, 1001, 1, 899990);
INSERT INTO detalle_venta VALUES (9010, 5007, 1002, 2, 239990);
INSERT INTO detalle_venta VALUES (9011, 5007, 1005, 2, 109915);
INSERT INTO detalle_venta VALUES (9012, 5010, 1005, 1, 109990);
INSERT INTO detalle_venta VALUES (9013, 5011, 1002, 1, 239990);
INSERT INTO detalle_venta VALUES (9014, 5011, 1003, 1, 79980);
INSERT INTO detalle_venta VALUES (9015, 5020, 1004, 1, 39990);

COMMIT;







/* ============================================================
   PROYECTO: TechMarket SpA
   ASIGNATURA: BDY1103 - Taller de Base de Datos
   EVALUACIÓN: EP1

   ARCHIVO: 04_objetos_plsql.sql
   RESPONSABLE: Pablo

   DESCRIPCIÓN:
   Este archivo contiene los objetos PL/SQL utilizados para
   procesar la clasificación comercial de los clientes y
   determinar los beneficios correspondientes.

   COMPONENTES:
   - Functions
   - Procedure
   - Package

   REGLAS DE NEGOCIO:
   - BRONZE:   menor a $300.000 -> 5%
   - SILVER:   $300.000 a $699.999 -> 10%
   - GOLD:     $700.000 a $1.499.999 -> 15%
   - PLATINUM: $1.500.000 o más -> 20%

   TABLAS PRINCIPALES:
   - CLIENTE
   - VENTA
   - BITACORA_BENEFICIOS

   INTEGRACIÓN:
   La lógica de este archivo se integrará posteriormente
   con los cursores y excepciones desarrollados por los
   demás integrantes del equipo.

   ============================================================ */
    /*==================================================
    FUNCTION: CALCULAR_BENEFICIO
    ==================================================*/

   CREATE OR REPLACE FUNCTION calcular_categorias(
    p_total_comprado IN NUMBER
   )
   RETURN VARCHAR2
   IS
   BEGIN
        IF p_total_comprado < 300000 THEN 
            RETURN 'BRONZE';
        ELSIF p_total_comprado < 700000 THEN
            RETURN 'SILVER';
        ELSIF p_total_comprado <1500000 THEN
            RETURN 'GOLD';
        ELSE
            RETURN 'PLATINUM';
        END IF;
    END calcular_categoria;
    /

    /*==================================================
    FUNCTION: CALCULAR_BENEFICIO
    ==================================================*/

     CREATE OR REPLACE FUNCTION calcular_beneficios(
        p_total_comprado IN NUMBER
     )
     RETURN NUMBER
     IS
     BEGIN
        IF p_total_comprado < 300000 THEN 
            RETURN '5';
        ELSIF p_total_comprado BETWEEN 300000 AND 699999 THEN 
            RETURN 10;
        ELSIF p_total_comprado BETWEEN 700000 AND 1499999 THEN
            RETURN 15;
        ELSE
            RETURN 20;
        END IF;
    END calcular_beneficio;
    /

    /*==================================================
    FUNCTION: PROCESAR_BENEFICIO
    ==================================================*/

    CREATE OR REPLACE PROCEDURE procesar_beneficios(
        p_id_sucursal IN NUMBER,
        p_fecha_desde IN DATE,
        p_fecha_hasta IN DATE
    )
    IS 
    v_total_comprado NUMBER;
    v_cantidad_compras NUMBER;
    v_categoria VARCHAR2(20);
    v_beneficio NUMBER;
    BEGIN
    END procesar_beneficios;
    /
     



/* ============================================================
   IMPORTANTE: Este codigo lo hice en OneCompiler(es casi lo mismo pero para que lo tengan en cuenta)

   PROYECTO: TechMarket SpA
   ASIGNATURA: BDY1103 - Taller de Base de Datos
   EVALUACION: EP1

   ARCHIVO: 02_DOCUMENTACION_TRIGGER_Y_BLOQUE_PLSQL
   RESPONSABLE: Danyer

   DESCRIPCION:
   Documentacion explicativa para el trigger de auditoria y el
   bloque anonimo PL/SQL encargados del control, validacion
   y manejo de excepciones en la asignacion de beneficios.

   COMPONENTES:
   - Trigger de Auditoria (TRG_AUDITORIA_BENEFICIOS)
   - Bloque PL/SQL (Control, Validaciones y Excepciones)

   REGLAS DE NEGOCIO:
   - Validacion estricta de parametros de entrada obligatorios.
   - Evaluacion de existencia previa del cliente.
   - Monto minimo requerido de $500.000 para asignacion de beneficio.
   - Auditoria automatica e imborrable de beneficios otorgados.

   TABLAS PRINCIPALES:
   - CLIENTE
   - VENTA
   - BITACORA_BENEFICIOS
   - AUDITORIA_BENEFICIOS

   INTEGRACION:
   Este codigo se integra directamente con las funciones desarrolladas
   por el resto del equipo.
   */


--TRIGGER DE AUDITORIA (TRAZABILIDAD DE BITACORA_BENEFICIOS)
CREATE OR REPLACE TRIGGER trg_auditoria_beneficios
AFTER INSERT ON bitacora_beneficios
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_beneficios (
        id_bitacora, operacion, usuario_bd, fecha_evento, categoria_nueva, total_nuevo
    ) VALUES (
        :NEW.id_bitacora, 'INSERT', USER, SYSDATE, :NEW.categoria_cliente, :NEW.total_compras
    );
    DBMS_OUTPUT.PUT_LINE('TRAZABILIDAD: Registro automatizado en AUDITORIA_BENEFICIOS para ID ' || :NEW.id_bitacora);
END;
/


-- BLOQUE PL/SQL DE CONTROL, VALIDACIONES Y EXCEPCIONES
DECLARE
    --Aqui solo tienen que cambiar v_id_cliente   NUMBER := 101; (pueden cambiarlo por 103 y 999)
    --Para que muestre todas las excepciones
    v_id_cliente   NUMBER := 101; 
    v_id_sucursal  NUMBER := 10;
    v_desde        DATE := DATE '2026-08-01';
    v_hasta        DATE := DATE '2026-08-31';
    
    v_nombre       VARCHAR2(120);
    v_cant_compras NUMBER := 0;
    v_total_monto  NUMBER := 0;
    
    -- Excepciones definidas por el usuario
    e_monto_insuficiente EXCEPTION;
    e_parametro_invalido EXCEPTION;
BEGIN
    -- Validaciones de entrada. Estos son Parametros obligatorios
    IF v_id_cliente IS NULL OR v_id_sucursal IS NULL OR v_desde IS NULL OR v_hasta IS NULL THEN
        RAISE e_parametro_invalido;
    END IF;

    IF v_desde > v_hasta THEN
        RAISE e_parametro_invalido;
    END IF;

    -- Validar existencia del cliente. Esta es la excepcion predefinida: NO_DATA_FOUND
    SELECT nombre 
    INTO v_nombre
    FROM cliente 
    WHERE id_cliente = v_id_cliente;

    -- Calcular compras acumuladas del periodo
    SELECT NVL(COUNT(*), 0), NVL(SUM(total), 0)
    INTO v_cant_compras, v_total_monto
    FROM venta
    WHERE id_cliente = v_id_cliente
      AND id_sucursal = v_id_sucursal
      AND fecha_venta BETWEEN v_desde AND v_hasta;

    --Regla de negocio y disparo de excepcion definida por el usuario
    IF v_total_monto < 500000 THEN
        RAISE e_monto_insuficiente;
    ELSE
        -- Insercion que activa la Trazabilidad (Trigger)
        INSERT INTO bitacora_beneficios (
            id_cliente, id_sucursal, periodo_desde, periodo_hasta,
            cantidad_compras, total_compras, categoria_cliente, porcentaje_beneficio, usuario_bd
        ) VALUES (
            v_id_cliente, v_id_sucursal, v_desde, v_hasta,
            v_cant_compras, v_total_monto, 'GOLD', 10.00, USER
        );
        
        DBMS_OUTPUT.PUT_LINE('EXITO: Beneficio asignado a ' || v_nombre || ' por total de $' || v_total_monto);
    END IF;

EXCEPTION
    -- Captura de validacion de entrada
    WHEN e_parametro_invalido THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: Los parametros de entrada son nulos o el rango de fechas es invalido.');

    -- Captura de excepcion predefinida
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: El cliente ID ' || v_id_cliente || ' no existe en la BD.');
        
    -- Captura de excepcion definida por Usuario
    WHEN e_monto_insuficiente THEN
        DBMS_OUTPUT.PUT_LINE('RECHAZADO: Cliente ' || v_nombre || ' acumula $' || v_total_monto || ' (Minimo requerido: $500.000).');
        
    -- Captura generica
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: Contactar al administrador DBA. ' || SQLERRM);
END;
/

-- CONSULTAS DE VERIFICACION
SELECT * FROM bitacora_beneficios;
SELECT * FROM auditoria_beneficios;




-- 1. TRIGGER PARA TRAZABILIDAD (Prueba P5)
CREATE OR REPLACE TRIGGER trg_auditoria_beneficios
AFTER INSERT OR UPDATE ON bitacora_beneficios
FOR EACH ROW
DECLARE
    v_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operacion := 'INSERT';
    ELSIF UPDATING THEN
        v_operacion := 'UPDATE';
    END IF;

    INSERT INTO auditoria_beneficios (
        id_bitacora,
        operacion,
        usuario_bd,
        categoria_anterior,
        categoria_nueva,
        total_anterior,
        total_nuevo
    ) VALUES (
        :NEW.id_bitacora,
        v_operacion,
        USER, -- Usuario de BD actual
        :OLD.categoria_cliente,
        :NEW.categoria_cliente,
        :OLD.total_compras,
        :NEW.total_compras
    );
END;
/

-- 2. BLOQUE DE EXCEPCIONES Y CONTROL (Pruebas P2, P3 y P4)
DECLARE
    -- Parametros de entrada
    v_sucursal_id NUMBER := 999; -- P2: Sucursal inexistente
    v_fecha_inicio DATE := TO_DATE('01/09/2026', 'DD/MM/YYYY');
    v_fecha_fin DATE := TO_DATE('31/08/2026', 'DD/MM/YYYY'); -- P3: Fecha fin antes de fecha inicio
    
    -- Variables para validacion
    v_existe_sucursal NUMBER;
    v_total_ventas NUMBER;

    -- Excepciones definidas por usuario
    ex_periodo_invalido EXCEPTION;
    ex_sin_ventas EXCEPTION;
    
BEGIN
    -- Validacion 1: Regla de negocio (P3)
    IF v_fecha_inicio > v_fecha_fin THEN
        RAISE ex_periodo_invalido;
    END IF;

    -- Validacion 2: Excepcion Oracle NO_DATA_FOUND (P2)
    SELECT id_sucursal INTO v_existe_sucursal 
    FROM sucursal 
    WHERE id_sucursal = v_sucursal_id;

    -- Validacion 3: Regla de negocio, periodo sin ventas (P4)
    SELECT COUNT(*) INTO v_total_ventas
    FROM venta
    WHERE id_sucursal = v_sucursal_id
    AND fecha_venta BETWEEN v_fecha_inicio AND v_fecha_fin;

    IF v_total_ventas = 0 THEN
        RAISE ex_sin_ventas;
    END IF;

    DBMS_OUTPUT.PUT_LINE('Validaciones exitosas. Listo para procesar.');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR (Oracle): La sucursal ingresada (' || v_sucursal_id || ') no existe en el sistema.');
    WHEN ex_periodo_invalido THEN
        DBMS_OUTPUT.PUT_LINE('ERROR (Negocio): El periodo es invalido. La fecha de inicio no puede ser posterior a la fecha de fin.');
    WHEN ex_sin_ventas THEN
         DBMS_OUTPUT.PUT_LINE('ERROR (Negocio): La sucursal ' || v_sucursal_id || ' no registro ventas en el periodo consultado.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR NO ESPERADO: ' || SQLERRM);
END;
/

