-- ============================================================
-- PROYECTO: TechMarket SpA
-- ASIGNATURA: BDY1103 - Taller de Base de Datos
-- EVALUACION: EP1
-- SCRIPT MAESTRO CORREGIDO
-- ============================================================

SET SERVEROUTPUT ON;

-- ============================================================
-- 1. ELIMINAR TABLAS ANTERIORES
-- ============================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE auditoria_beneficios CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE bitacora_beneficios CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE detalle_venta CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE venta CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE producto CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE cliente CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE sucursal CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- 2. CREACION DE TABLAS
-- ============================================================

CREATE TABLE sucursal (
    id_sucursal NUMBER(4)
        CONSTRAINT pk_sucursal PRIMARY KEY,
    nombre VARCHAR2(80) NOT NULL,
    comuna VARCHAR2(80) NOT NULL
);

CREATE TABLE cliente (
    id_cliente NUMBER(6)
        CONSTRAINT pk_cliente PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    correo VARCHAR2(150)
        CONSTRAINT uq_cliente_correo UNIQUE,
    estado VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL,
    fecha_registro DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT ck_cliente_estado
        CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE producto (
    id_producto NUMBER(6)
        CONSTRAINT pk_producto PRIMARY KEY,
    nombre_producto VARCHAR2(120) NOT NULL,
    categoria VARCHAR2(60) NOT NULL,
    precio NUMBER(12,2) NOT NULL,
    stock NUMBER(8) DEFAULT 0 NOT NULL,

    CONSTRAINT ck_producto_precio
        CHECK (precio > 0),

    CONSTRAINT ck_producto_stock
        CHECK (stock >= 0)
);

CREATE TABLE venta (
    id_venta NUMBER(8)
        CONSTRAINT pk_venta PRIMARY KEY,
    id_sucursal NUMBER(4) NOT NULL,
    id_cliente NUMBER(6) NOT NULL,
    fecha_venta DATE NOT NULL,
    total NUMBER(14,2) NOT NULL,

    CONSTRAINT fk_venta_sucursal
        FOREIGN KEY (id_sucursal)
        REFERENCES sucursal(id_sucursal),

    CONSTRAINT fk_venta_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente),

    CONSTRAINT ck_venta_total
        CHECK (total >= 0)
);

CREATE TABLE detalle_venta (
    id_detalle NUMBER(10)
        CONSTRAINT pk_detalle_venta PRIMARY KEY,
    id_venta NUMBER(8) NOT NULL,
    id_producto NUMBER(6) NOT NULL,
    cantidad NUMBER(6) NOT NULL,
    precio_unitario NUMBER(12,2) NOT NULL,

    CONSTRAINT fk_detalle_venta
        FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta),

    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto),

    CONSTRAINT ck_detalle_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_detalle_precio
        CHECK (precio_unitario > 0)
);

CREATE TABLE bitacora_beneficios (
    id_bitacora NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_bitacora_beneficios PRIMARY KEY,

    id_cliente NUMBER(6) NOT NULL,
    id_sucursal NUMBER(4) NOT NULL,
    periodo_desde DATE NOT NULL,
    periodo_hasta DATE NOT NULL,
    cantidad_compras NUMBER(6) NOT NULL,
    total_compras NUMBER(14,2) NOT NULL,
    categoria_cliente VARCHAR2(20) NOT NULL,
    porcentaje_beneficio NUMBER(5,2) NOT NULL,
    fecha_proceso DATE DEFAULT SYSDATE NOT NULL,
    usuario_bd VARCHAR2(128),
    fecha_actualizacion DATE,

    CONSTRAINT fk_bitacora_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente),

    CONSTRAINT fk_bitacora_sucursal
        FOREIGN KEY (id_sucursal)
        REFERENCES sucursal(id_sucursal)
);

CREATE TABLE auditoria_beneficios (
    id_auditoria NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_auditoria_beneficios PRIMARY KEY,

    id_bitacora NUMBER,
    operacion VARCHAR2(10) NOT NULL,
    usuario_bd VARCHAR2(128) NOT NULL,
    fecha_evento DATE DEFAULT SYSDATE NOT NULL,

    categoria_anterior VARCHAR2(20),
    categoria_nueva VARCHAR2(20),

    total_anterior NUMBER(14,2),
    total_nuevo NUMBER(14,2)
);

-- ============================================================
-- 3. INDICES
-- ============================================================

CREATE INDEX idx_venta_sucursal_fecha
ON venta(id_sucursal, fecha_venta);

CREATE INDEX idx_venta_cliente
ON venta(id_cliente);

CREATE INDEX idx_detalle_venta
ON detalle_venta(id_venta);

-- ============================================================
-- 4. DATOS INICIALES
-- ============================================================

INSERT INTO sucursal
VALUES (10, 'Antonio Varas', 'Providencia');

INSERT INTO sucursal
VALUES (20, 'Plaza Oeste', 'Cerrillos');

INSERT INTO sucursal
VALUES (30, 'Vina Centro', 'Vina del Mar');


INSERT INTO cliente
VALUES (
    101,
    'Ana Torres',
    'ana.torres@correo.cl',
    'ACTIVO',
    DATE '2026-01-15'
);

INSERT INTO cliente
VALUES (
    102,
    'Pedro Diaz',
    'pedro.diaz@correo.cl',
    'ACTIVO',
    DATE '2026-02-10'
);

INSERT INTO cliente
VALUES (
    103,
    'Maria Soto',
    'maria.soto@correo.cl',
    'ACTIVO',
    DATE '2026-03-05'
);

INSERT INTO cliente
VALUES (
    104,
    'Carlos Rojas',
    'carlos.rojas@correo.cl',
    'ACTIVO',
    DATE '2026-03-20'
);

INSERT INTO cliente
VALUES (
    105,
    'Sofia Perez',
    'sofia.perez@correo.cl',
    'INACTIVO',
    DATE '2026-04-02'
);


INSERT INTO producto
VALUES (
    1001,
    'Notebook Pro 14',
    'Notebook',
    899990,
    12
);

INSERT INTO producto
VALUES (
    1002,
    'Monitor 27 IPS',
    'Monitor',
    239990,
    25
);

INSERT INTO producto
VALUES (
    1003,
    'Teclado mecanico',
    'Periferico',
    79990,
    40
);

INSERT INTO producto
VALUES (
    1004,
    'Mouse inalambrico',
    'Periferico',
    39990,
    60
);

INSERT INTO producto
VALUES (
    1005,
    'SSD NVMe 1TB',
    'Almacenamiento',
    109990,
    30
);

-- ============================================================
-- 5. VENTAS
-- ============================================================

-- Sucursal 10 - Agosto 2026

INSERT INTO venta
VALUES (
    5001,
    10,
    101,
    DATE '2026-08-03',
    899990
);

INSERT INTO venta
VALUES (
    5002,
    10,
    101,
    DATE '2026-08-12',
    279980
);

INSERT INTO venta
VALUES (
    5003,
    10,
    101,
    DATE '2026-08-25',
    159980
);

INSERT INTO venta
VALUES (
    5004,
    10,
    102,
    DATE '2026-08-07',
    239990
);

INSERT INTO venta
VALUES (
    5005,
    10,
    102,
    DATE '2026-08-19',
    519970
);

INSERT INTO venta
VALUES (
    5006,
    10,
    103,
    DATE '2026-08-11',
    219980
);

INSERT INTO venta
VALUES (
    5007,
    10,
    104,
    DATE '2026-08-15',
    1599800
);

-- Sucursal 20 - Agosto 2026

INSERT INTO venta
VALUES (
    5010,
    20,
    101,
    DATE '2026-08-05',
    109990
);

INSERT INTO venta
VALUES (
    5011,
    20,
    103,
    DATE '2026-08-17',
    319970
);

-- Sucursal 10 - Septiembre 2026

INSERT INTO venta
VALUES (
    5020,
    10,
    102,
    DATE '2026-09-02',
    39990
);

-- ============================================================
-- 6. DETALLE DE VENTAS
-- ============================================================

INSERT INTO detalle_venta
VALUES (9001, 5001, 1001, 1, 899990);

INSERT INTO detalle_venta
VALUES (9002, 5002, 1002, 1, 239990);

INSERT INTO detalle_venta
VALUES (9003, 5002, 1004, 1, 39990);

INSERT INTO detalle_venta
VALUES (9004, 5003, 1003, 2, 79990);

INSERT INTO detalle_venta
VALUES (9005, 5004, 1002, 1, 239990);

INSERT INTO detalle_venta
VALUES (9006, 5005, 1001, 1, 479980);

INSERT INTO detalle_venta
VALUES (9007, 5005, 1004, 1, 39990);

INSERT INTO detalle_venta
VALUES (9008, 5006, 1005, 2, 109990);

INSERT INTO detalle_venta
VALUES (9009, 5007, 1001, 1, 899990);

INSERT INTO detalle_venta
VALUES (9010, 5007, 1002, 2, 239990);

INSERT INTO detalle_venta
VALUES (9011, 5007, 1005, 2, 109915);

INSERT INTO detalle_venta
VALUES (9012, 5010, 1005, 1, 109990);

INSERT INTO detalle_venta
VALUES (9013, 5011, 1002, 1, 239990);

INSERT INTO detalle_venta
VALUES (9014, 5011, 1003, 1, 79980);

INSERT INTO detalle_venta
VALUES (9015, 5020, 1004, 1, 39990);

COMMIT;

-- ============================================================
-- 7. FUNCTION: CALCULAR_CATEGORIA
-- ============================================================

CREATE OR REPLACE FUNCTION calcular_categoria(
    p_total_comprado IN NUMBER
)
RETURN VARCHAR2
IS
BEGIN

    IF p_total_comprado < 300000 THEN
        RETURN 'BRONZE';

    ELSIF p_total_comprado < 700000 THEN
        RETURN 'SILVER';

    ELSIF p_total_comprado < 1500000 THEN
        RETURN 'GOLD';

    ELSE
        RETURN 'PLATINUM';
    END IF;

END calcular_categoria;
/

-- ============================================================
-- 8. FUNCTION: CALCULAR_BENEFICIO
-- ============================================================

CREATE OR REPLACE FUNCTION calcular_beneficio(
    p_total_comprado IN NUMBER
)
RETURN NUMBER
IS
BEGIN

    IF p_total_comprado < 300000 THEN
        RETURN 5;

    ELSIF p_total_comprado < 700000 THEN
        RETURN 10;

    ELSIF p_total_comprado < 1500000 THEN
        RETURN 15;

    ELSE
        RETURN 20;
    END IF;

END calcular_beneficio;
/

-- ============================================================
-- 9. RECORD + VARRAY
-- ============================================================

DECLARE

    TYPE cliente_record IS RECORD (
        id_cliente CLIENTE.ID_CLIENTE%TYPE,
        nombre_cliente CLIENTE.NOMBRE%TYPE,
        cantidad_compras NUMBER,
        total_comprado NUMBER,
        categoria VARCHAR2(20),
        beneficio NUMBER
    );

    v_cliente cliente_record;

    TYPE beneficios_varray IS VARRAY(4) OF NUMBER;

    v_beneficios beneficios_varray :=
        beneficios_varray(5, 10, 15, 20);

BEGIN

    SELECT
        c.id_cliente,
        c.nombre,
        COUNT(v.id_venta),
        NVL(SUM(v.total), 0)

    INTO
        v_cliente.id_cliente,
        v_cliente.nombre_cliente,
        v_cliente.cantidad_compras,
        v_cliente.total_comprado

    FROM cliente c

    LEFT JOIN venta v
        ON c.id_cliente = v.id_cliente

    WHERE c.id_cliente = 101

    GROUP BY
        c.id_cliente,
        c.nombre;

    v_cliente.categoria :=
        calcular_categoria(
            v_cliente.total_comprado
        );

    v_cliente.beneficio :=
        calcular_beneficio(
            v_cliente.total_comprado
        );

    DBMS_OUTPUT.PUT_LINE(
        'ID Cliente: ' ||
        v_cliente.id_cliente
    );

    DBMS_OUTPUT.PUT_LINE(
        'Nombre: ' ||
        v_cliente.nombre_cliente
    );

    DBMS_OUTPUT.PUT_LINE(
        'Cantidad compras: ' ||
        v_cliente.cantidad_compras
    );

    DBMS_OUTPUT.PUT_LINE(
        'Total comprado: $' ||
        v_cliente.total_comprado
    );

    DBMS_OUTPUT.PUT_LINE(
        'Categoria: ' ||
        v_cliente.categoria
    );

    DBMS_OUTPUT.PUT_LINE(
        'Beneficio: ' ||
        v_cliente.beneficio || '%'
    );

    DBMS_OUTPUT.PUT_LINE(
        'Beneficios disponibles: ' ||
        v_beneficios(1) || '%, ' ||
        v_beneficios(2) || '%, ' ||
        v_beneficios(3) || '%, ' ||
        v_beneficios(4) || '%'
    );

END;
/

-- ============================================================
-- 10. CURSORES PARAMETRIZADOS + LOOP ANIDADO
-- ============================================================

DECLARE

    v_id_sucursal NUMBER := 10;

    v_fecha_desde DATE :=
        DATE '2026-08-01';

    v_fecha_hasta DATE :=
        DATE '2026-08-31';

    -- CURSOR MAESTRO
    CURSOR cur_clientes(
        p_id_sucursal NUMBER,
        p_fecha_desde DATE,
        p_fecha_hasta DATE
    )
    IS

        SELECT DISTINCT
            c.id_cliente,
            c.nombre

        FROM cliente c

        JOIN venta v
            ON c.id_cliente = v.id_cliente

        WHERE v.id_sucursal = p_id_sucursal

        AND v.fecha_venta
            BETWEEN p_fecha_desde
            AND p_fecha_hasta

        ORDER BY c.id_cliente;

    -- CURSOR DETALLE
    CURSOR cur_ventas(
        p_id_cliente NUMBER,
        p_id_sucursal NUMBER,
        p_fecha_desde DATE,
        p_fecha_hasta DATE
    )
    IS

        SELECT
            id_venta,
            fecha_venta,
            total

        FROM venta

        WHERE id_cliente = p_id_cliente

        AND id_sucursal = p_id_sucursal

        AND fecha_venta
            BETWEEN p_fecha_desde
            AND p_fecha_hasta

        ORDER BY fecha_venta;

    v_cantidad_compras NUMBER;

    v_total_comprado NUMBER;

BEGIN

    -- LOOP MAESTRO
    FOR cliente IN cur_clientes(
        v_id_sucursal,
        v_fecha_desde,
        v_fecha_hasta
    )
    LOOP

        v_cantidad_compras := 0;

        v_total_comprado := 0;

        DBMS_OUTPUT.PUT_LINE(
            '--------------------------------'
        );

        DBMS_OUTPUT.PUT_LINE(
            'Cliente: ' ||
            cliente.id_cliente ||
            ' - ' ||
            cliente.nombre
        );

        -- LOOP DETALLE
        FOR venta IN cur_ventas(
            cliente.id_cliente,
            v_id_sucursal,
            v_fecha_desde,
            v_fecha_hasta
        )
        LOOP

            v_cantidad_compras :=
                v_cantidad_compras + 1;

            v_total_comprado :=
                v_total_comprado + venta.total;

            DBMS_OUTPUT.PUT_LINE(
                '  Venta: ' ||
                venta.id_venta ||
                ' | Fecha: ' ||
                TO_CHAR(
                    venta.fecha_venta,
                    'DD/MM/YYYY'
                ) ||
                ' | Total: $' ||
                venta.total
            );

        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            'Cantidad compras: ' ||
            v_cantidad_compras
        );

        DBMS_OUTPUT.PUT_LINE(
            'Total comprado: $' ||
            v_total_comprado
        );

        DBMS_OUTPUT.PUT_LINE(
            'Categoria: ' ||
            calcular_categoria(
                v_total_comprado
            )
        );

        DBMS_OUTPUT.PUT_LINE(
            'Beneficio: ' ||
            calcular_beneficio(
                v_total_comprado
            ) ||
            '%'
        );

    END LOOP;

END;
/

-- ============================================================
-- 11. PROCEDURE: PROCESAR_BENEFICIOS
-- ============================================================

CREATE OR REPLACE PROCEDURE procesar_beneficios(
    p_id_sucursal IN NUMBER,
    p_fecha_desde IN DATE,
    p_fecha_hasta IN DATE
)
IS

    v_total_comprado NUMBER;

    v_cantidad_compras NUMBER;

    v_categoria VARCHAR2(20);

    v_beneficio NUMBER;

BEGIN

    FOR cliente IN (

        SELECT
            c.id_cliente,
            c.nombre

        FROM cliente c

        JOIN venta v
            ON c.id_cliente = v.id_cliente

        WHERE v.id_sucursal = p_id_sucursal

        AND v.fecha_venta
            BETWEEN p_fecha_desde
            AND p_fecha_hasta

        GROUP BY
            c.id_cliente,
            c.nombre

        ORDER BY c.id_cliente

    )
    LOOP

        SELECT
            COUNT(v.id_venta),
            NVL(SUM(v.total), 0)

        INTO
            v_cantidad_compras,
            v_total_comprado

        FROM venta v

        WHERE v.id_cliente =
            cliente.id_cliente

        AND v.id_sucursal =
            p_id_sucursal

        AND v.fecha_venta
            BETWEEN p_fecha_desde
            AND p_fecha_hasta;

        v_categoria :=
            calcular_categoria(
                v_total_comprado
            );

        v_beneficio :=
            calcular_beneficio(
                v_total_comprado
            );

        INSERT INTO bitacora_beneficios (

            id_cliente,
            id_sucursal,
            periodo_desde,
            periodo_hasta,
            cantidad_compras,
            total_compras,
            categoria_cliente,
            porcentaje_beneficio,
            fecha_proceso,
            usuario_bd,
            fecha_actualizacion

        )
        VALUES (

            cliente.id_cliente,
            p_id_sucursal,
            p_fecha_desde,
            p_fecha_hasta,
            v_cantidad_compras,
            v_total_comprado,
            v_categoria,
            v_beneficio,
            SYSDATE,
            USER,
            SYSDATE

        );

        DBMS_OUTPUT.PUT_LINE(
            'Cliente: ' ||
            cliente.id_cliente ||
            ' | Compras: ' ||
            v_cantidad_compras ||
            ' | Total: $' ||
            v_total_comprado ||
            ' | Categoria: ' ||
            v_categoria ||
            ' | Beneficio: ' ||
            v_beneficio ||
            '%'
        );

    END LOOP;

END procesar_beneficios;
/

-- ============================================================
-- 12. PACKAGE
-- ============================================================

CREATE OR REPLACE PACKAGE techmarket_beneficios AS

    FUNCTION calcular_categoria(
        p_total_comprado IN NUMBER
    )
    RETURN VARCHAR2;

    FUNCTION calcular_beneficio(
        p_total_comprado IN NUMBER
    )
    RETURN NUMBER;

    PROCEDURE procesar_beneficios(
        p_id_sucursal IN NUMBER,
        p_fecha_desde IN DATE,
        p_fecha_hasta IN DATE
    );

END techmarket_beneficios;
/

-- ============================================================
-- 13. PACKAGE BODY
-- ============================================================

CREATE OR REPLACE PACKAGE BODY techmarket_beneficios AS

    FUNCTION calcular_categoria(
        p_total_comprado IN NUMBER
    )
    RETURN VARCHAR2
    IS
    BEGIN

        IF p_total_comprado < 300000 THEN
            RETURN 'BRONZE';

        ELSIF p_total_comprado < 700000 THEN
            RETURN 'SILVER';

        ELSIF p_total_comprado < 1500000 THEN
            RETURN 'GOLD';

        ELSE
            RETURN 'PLATINUM';
        END IF;

    END calcular_categoria;


    FUNCTION calcular_beneficio(
        p_total_comprado IN NUMBER
    )
    RETURN NUMBER
    IS
    BEGIN

        IF p_total_comprado < 300000 THEN
            RETURN 5;

        ELSIF p_total_comprado < 700000 THEN
            RETURN 10;

        ELSIF p_total_comprado < 1500000 THEN
            RETURN 15;

        ELSE
            RETURN 20;
        END IF;

    END calcular_beneficio;


    PROCEDURE procesar_beneficios(
        p_id_sucursal IN NUMBER,
        p_fecha_desde IN DATE,
        p_fecha_hasta IN DATE
    )
    IS

        v_total_comprado NUMBER;

        v_cantidad_compras NUMBER;

        v_categoria VARCHAR2(20);

        v_beneficio NUMBER;

    BEGIN

        FOR cliente IN (

            SELECT
                c.id_cliente,
                c.nombre

            FROM cliente c

            JOIN venta v
                ON c.id_cliente = v.id_cliente

            WHERE v.id_sucursal =
                p_id_sucursal

            AND v.fecha_venta
                BETWEEN p_fecha_desde
                AND p_fecha_hasta

            GROUP BY
                c.id_cliente,
                c.nombre

            ORDER BY c.id_cliente

        )
        LOOP

            SELECT
                COUNT(v.id_venta),
                NVL(SUM(v.total), 0)

            INTO
                v_cantidad_compras,
                v_total_comprado

            FROM venta v

            WHERE v.id_cliente =
                cliente.id_cliente

            AND v.id_sucursal =
                p_id_sucursal

            AND v.fecha_venta
                BETWEEN p_fecha_desde
                AND p_fecha_hasta;

            v_categoria :=
                calcular_categoria(
                    v_total_comprado
                );

            v_beneficio :=
                calcular_beneficio(
                    v_total_comprado
                );

            INSERT INTO bitacora_beneficios (

                id_cliente,
                id_sucursal,
                periodo_desde,
                periodo_hasta,
                cantidad_compras,
                total_compras,
                categoria_cliente,
                porcentaje_beneficio,
                fecha_proceso,
                usuario_bd,
                fecha_actualizacion

            )
            VALUES (

                cliente.id_cliente,
                p_id_sucursal,
                p_fecha_desde,
                p_fecha_hasta,
                v_cantidad_compras,
                v_total_comprado,
                v_categoria,
                v_beneficio,
                SYSDATE,
                USER,
                SYSDATE

            );

        END LOOP;

    END procesar_beneficios;

END techmarket_beneficios;
/

-- ============================================================
-- 14. TRIGGER DE AUDITORIA
-- ============================================================

CREATE OR REPLACE TRIGGER trg_auditoria_beneficios
AFTER INSERT OR UPDATE
ON bitacora_beneficios
FOR EACH ROW

DECLARE

    v_operacion VARCHAR2(10);

BEGIN

    IF INSERTING THEN

        v_operacion := 'INSERT';

    ELSIF UPDATING THEN

        v_operacion := 'UPDATE';

    END IF;

    INSERT INTO auditoria_beneficios (

        id_bitacora,
        operacion,
        usuario_bd,
        fecha_evento,
        categoria_anterior,
        categoria_nueva,
        total_anterior,
        total_nuevo

    )
    VALUES (

        :NEW.id_bitacora,
        v_operacion,
        USER,
        SYSDATE,
        :OLD.categoria_cliente,
        :NEW.categoria_cliente,
        :OLD.total_compras,
        :NEW.total_compras

    );

    DBMS_OUTPUT.PUT_LINE(
        'TRAZABILIDAD: Registro automatizado en AUDITORIA_BENEFICIOS para ID ' ||
        :NEW.id_bitacora
    );

END;
/

-- ============================================================
-- 15. P2 - SUCURSAL INEXISTENTE
-- EXCEPCION PREDEFINIDA NO_DATA_FOUND
-- ============================================================

DECLARE

    v_sucursal_id NUMBER := 999;

    v_sucursal NUMBER;

BEGIN

    SELECT id_sucursal
    INTO v_sucursal

    FROM sucursal

    WHERE id_sucursal = v_sucursal_id;

    DBMS_OUTPUT.PUT_LINE(
        'Sucursal encontrada: ' ||
        v_sucursal
    );

EXCEPTION

    WHEN NO_DATA_FOUND THEN

        DBMS_OUTPUT.PUT_LINE(
            'ERROR: La sucursal ' ||
            v_sucursal_id ||
            ' no existe en el sistema.'
        );

    WHEN OTHERS THEN

        DBMS_OUTPUT.PUT_LINE(
            'ERROR NO ESPERADO: ' ||
            SQLERRM
        );

END;
/

-- ============================================================
-- 16. P3 - PERIODO INVALIDO
-- EXCEPCION DEFINIDA POR EL USUARIO
-- ============================================================

DECLARE

    v_fecha_inicio DATE :=
        DATE '2026-08-31';

    v_fecha_fin DATE :=
        DATE '2026-08-01';

    ex_periodo_invalido EXCEPTION;

BEGIN

    IF v_fecha_inicio > v_fecha_fin THEN

        RAISE ex_periodo_invalido;

    END IF;

    DBMS_OUTPUT.PUT_LINE(
        'Periodo valido.'
    );

EXCEPTION

    WHEN ex_periodo_invalido THEN

        DBMS_OUTPUT.PUT_LINE(
            'ERROR: El periodo es invalido.'
        );

        DBMS_OUTPUT.PUT_LINE(
            'La fecha de inicio no puede ser posterior a la fecha de fin.'
        );

    WHEN OTHERS THEN

        DBMS_OUTPUT.PUT_LINE(
            'ERROR NO ESPERADO: ' ||
            SQLERRM
        );

END;
/

-- ============================================================
-- 17. P4 - SUCURSAL SIN VENTAS
-- EXCEPCION DEFINIDA POR EL USUARIO
-- ============================================================

DECLARE

    v_sucursal_id NUMBER := 20;

    v_fecha_inicio DATE :=
        DATE '2026-09-01';

    v_fecha_fin DATE :=
        DATE '2026-09-30';

    v_total_ventas NUMBER;

    ex_sin_ventas EXCEPTION;

BEGIN

    SELECT COUNT(*)

    INTO v_total_ventas

    FROM venta

    WHERE id_sucursal = v_sucursal_id

    AND fecha_venta
        BETWEEN v_fecha_inicio
        AND v_fecha_fin;

    IF v_total_ventas = 0 THEN

        RAISE ex_sin_ventas;

    END IF;

    DBMS_OUTPUT.PUT_LINE(
        'La sucursal tiene ventas en el periodo.'
    );

EXCEPTION

    WHEN ex_sin_ventas THEN

        DBMS_OUTPUT.PUT_LINE(
            'ERROR: La sucursal ' ||
            v_sucursal_id ||
            ' no registro ventas en el periodo.'
        );

    WHEN OTHERS THEN

        DBMS_OUTPUT.PUT_LINE(
            'ERROR NO ESPERADO: ' ||
            SQLERRM
        );

END;
/

-- ============================================================
-- 18. P1 - PROCESAMIENTO NORMAL
-- ============================================================

BEGIN

    techmarket_beneficios.procesar_beneficios(

        10,

        DATE '2026-08-01',

        DATE '2026-08-31'

    );

END;
/

COMMIT;

-- ============================================================
-- 19. CONSULTAR BITACORA
-- ============================================================

SELECT
    id_bitacora,
    id_cliente,
    id_sucursal,
    periodo_desde,
    periodo_hasta,
    cantidad_compras,
    total_compras,
    categoria_cliente,
    porcentaje_beneficio,
    fecha_proceso,
    usuario_bd,
    fecha_actualizacion

FROM bitacora_beneficios

ORDER BY id_bitacora;

-- ============================================================
-- 20. CONSULTAR AUDITORIA
-- ============================================================

SELECT
    id_auditoria,
    id_bitacora,
    operacion,
    usuario_bd,
    fecha_evento,
    categoria_anterior,
    categoria_nueva,
    total_anterior,
    total_nuevo

FROM auditoria_beneficios

ORDER BY id_auditoria;